version: '3.3'

services:
  cd-config:
    image: cd-config:latest

  cd-gateway:
    image: cd-gateway:latest
    ports:
      - "8761:8761"

  cd-discovery:
    image: cd-discovery:latest
    ports:
      - "8765:8765"

  cd-query:
    image: cd-query:latest
    depends_on:
      - elasticsearch
      - mongo
    environment:
      - WAIT_HOSTS=elasticsearch:9200,mongo:27017

  cd-service:
    image: contact-discovery-service:latest
    depends_on:
      - elasticsearch
      - mongo
    environment:
      - WAIT_HOSTS=elasticsearch:9200,mongo:27017

  elasticsearch:
    image: elasticsearch:latest
    command: elasticsearch
    environment:
      - action.auto_create_index=true
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3

  mongo_connector:
    build:
      ./mongo-connector
    depends_on:
      - mongo
      - elasticsearch
    environment:
      - WAIT_HOSTS=elasticsearch:9200,mongo:27017

  mongo:
    image: mongo:latest
    command: "mongod --replSet rs0"
    ports:
      - "27017:27017"